version: "3"
services:

        database:
                build: ./BD/
                image: mysql
                ports:
                        - 3306:3306
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=inscricao
        backend:
                build: ./Back
                image: ubuntu
                ports:
                        - 5000:5000
                external_links:
                        - db:docker-mysql
                environment:
                        DB_HOST: docker-mysql
        # frontend:
        #         build: ./Web2
        #         image: debian
        #         ports:
        #                - 80:80
        #         links:
        #                - backend



