version: "3"
services:
        db :
                build: ./BD/
                image: bd
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=inscricao
        
        backend:
                build: ./Back/
                image: backend
                ports:
                        - "80:5000"
                depends_on:
                        - "db"
                links:
                        - db:docker-mysql
                environment:
                        DB_HOST: docker-mysql
        
        # frontend:
        #         build: ./Web2
        #         image: debian
        #         ports:
        #                - 80:80
        #         links:
        #                - backend



